{
    'name': "pokedex_app",
    'description': "Pokedex App with PokéAPI Integration",
    'author': "Andre Romero",
    'category': 'Customizations',
    'version': '0.1',
    'depends': ['base', 'web', 'base_automation'],
    'data': [
        'security/ir.model.access.csv',
        'data/scheduled_xp.xml',
        'views/templates.xml',
        'wizards/views/catch_wizard_views.xml',
        'wizards/views/search_wizard_views.xml',
        'views/views.xml',
        'data/pokemon_level_up.xml',
        'data/api_actions.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}